version: '3'

services:
  followers-api:
    container_name: "followers-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_followers_db
      DB_PORT: 5432

  postgres_followers_db:
    container_name: postgres_db_follows
    image: postgres:12
    ports:
          - 5434:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
#    volumes:
#      - followerdata:/var/lib/postgresql/data
#
#  volumes:
#    pgdata:
#      external:true