version: '3'

services:
  followers-api:
    container_name: "followers-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_followers_db
      DB_PORT: 5432

  postgres_followers_db:
    container_name: postgres_followers_db
    image: postgres:12
    ports:
          - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db